@ECHO OFF
CD ..
REM DELTREE /Y DISTRIB\BIN\*.*
REM DELTREE /Y DISTRIB\LIB\*.*
MKDIR obj
MKDIR distrib\bin
MKDIR distrib\lib
COPY CONTRIB\LIBSQLITE.DLL distrib\lib
CLS

CD WIN32
CD CONFIG
NMAKE /C /S /F CONFIG.MAK
CD ..\GWMON
NMAKE /C /S /F GWMON.MAK
CD ..
CD ..
CD DBUTIL
NMAKE /C /S /F DBUTIL.MAK
CD ..\HTTPD
NMAKE /C /S /F HTTPD.MAK
CD ..\POP3D
NMAKE /C /S /F POP3D.MAK
CD ..\SMTPD
NMAKE /C /S /F SMTPD.MAK
CD ..\MODULES
CALL MAKE.BAT
CD ..
