#!/bin/sh

case "$1" in
'build')
	if [ ! -r "sqlite-2.8.11.tar.gz" ]; then
		echo "sqlite source not found"
		exit 0
	fi
	if [ ! -r "sqlite/configure" ]; then
		tar zxf sqlite-2.8.11.tar.gz
	fi
	mkdir -p build
	cd build
	if [ ! -r "Makefile" ]; then
		../sqlite/configure --disable-static
	fi
	if [ "`uname`" != "Linux" ]; then
		gmake -s
	else
		make -s
	fi
	cd ..
	if [ -r "build/.libs/libsqlite.so.0.8.6" ]; then
		strip build/.libs/libsqlite.so.0.8.6
		cp -p build/.libs/libsqlite.so.0.8.6 ../distrib/lib/libsqlite.so
	elif [ -r "build/.libs/libsqlite.so.8" ]; then
		strip build/.libs/libsqlite.so.8
		cp -p build/.libs/libsqlite.so.8 ../distrib/lib/libsqlite.so
	fi
	;;
'clean')
	rm -rf sqlite
	rm -rf build
	;;
*)
	echo "Usage: $0 {build|clean}"
esac
exit 0
