# Makefile for NullLogic Groupware mods

all: _mod_admin _mod_bookmarks _mod_calendar _mod_calls _mod_cgi \
	_mod_contacts _mod_files _mod_forums _mod_html _mod_mail \
	_mod_messages _mod_notes _mod_orders _mod_profile _mod_searches \
	_mod_tasks _mod_xmlrpc

_mod_admin:
	@cd mod_admin;make

_mod_bookmarks:
	@cd mod_bookmarks;make

_mod_calendar:
	@cd mod_calendar;make

_mod_calls:
	@cd mod_calls;make

_mod_cgi:
	@cd mod_cgi;make

_mod_contacts:
	@cd mod_contacts;make

_mod_files:
	@cd mod_files;make

_mod_forums:
	@cd mod_forums;make

_mod_html:
	@cd mod_html;make

_mod_mail:
	@cd mod_mail;make

_mod_messages:
	@cd mod_messages;make

_mod_notes:
	@cd mod_notes;make

_mod_orders:
	@cd mod_orders;make

_mod_profile:
	@cd mod_profile;make

_mod_searches:
	@cd mod_searches;make

_mod_tasks:
	@cd mod_tasks;make

_mod_xmlrpc:
	@cd mod_xmlrpc;make

clean:
	@cd mod_admin;make clean
	@cd mod_bookmarks;make clean
	@cd mod_calendar;make clean
	@cd mod_calls;make clean
	@cd mod_cgi;make clean
	@cd mod_contacts;make clean
	@cd mod_files;make clean
	@cd mod_forums;make clean
	@cd mod_html;make clean
	@cd mod_mail;make clean
	@cd mod_messages;make clean
	@cd mod_notes;make clean
	@cd mod_orders;make clean
	@cd mod_profile;make clean
	@cd mod_searches;make clean
	@cd mod_tasks;make clean
	@cd mod_xmlrpc;make clean
	@rm -f *~
