@ECHO OFF
CD MOD_ADMIN
NMAKE /C /S /F MOD_ADMIN.MAK
CD ..
CD MOD_BOOKMARKS
NMAKE /C /S /F MOD_BOOKMARKS.MAK
CD ..
CD MOD_CALENDAR
NMAKE /C /S /F MOD_CALENDAR.MAK
CD ..
CD MOD_CALLS
NMAKE /C /S /F MOD_CALLS.MAK
CD ..
CD MOD_CGI
NMAKE /C /S /F MOD_CGI.MAK
CD ..
CD MOD_CONTACTS
NMAKE /C /S /F MOD_CONTACTS.MAK
CD ..
CD MOD_FILES
NMAKE /C /S /F MOD_FILES.MAK
CD ..
CD MOD_FORUMS
NMAKE /C /S /F MOD_FORUMS.MAK
CD ..
CD MOD_HTML
NMAKE /C /S /F MOD_HTML.MAK
CD ..
CD MOD_MAIL
NMAKE /C /S /F MOD_MAIL.MAK
CD ..
CD MOD_MESSAGES
NMAKE /C /S /F MOD_MESSAGES.MAK
CD ..
CD MOD_NOTES
NMAKE /C /S /F MOD_NOTES.MAK
CD ..
CD MOD_ORDERS
NMAKE /C /S /F MOD_ORDERS.MAK
CD ..
CD MOD_PROFILE
NMAKE /C /S /F MOD_PROFILE.MAK
CD ..
CD MOD_PROJECTS
NMAKE /C /S /F MOD_PROJECTS.MAK
CD ..
CD MOD_SEARCHES
NMAKE /C /S /F MOD_SEARCHES.MAK
CD ..
CD MOD_TASKS
NMAKE /C /S /F MOD_TASKS.MAK
CD ..
CD MOD_XMLRPC
NMAKE /C /S /F MOD_XMLRPC.MAK
CD ..
