#!/bin/sh
OUTFILE=nullgroupware-1.2.3-x86-linux
FILEDATE="2003-08-02 01:02"

build_clean() {
	rm -f distrib/setup
#	rm -f distrib/bin/*
}

build_pack() {
	rm -rf ${OUTFILE}
	rm -rf ${OUTFILE}.tar.gz
	cp -av other/rc.groupware distrib/bin/rc.groupware
	cp -av other/setup distrib/setup

	chmod 0755 distrib -R
	chmod 0644 distrib/COPYING
	chmod 0644 distrib/COPYRIGHT.txt
	chmod 0644 distrib/README.txt
	chmod 0755 distrib/setup
	chmod 0755 distrib/bin/*
	chmod 0755 distrib/cgi-bin/*
	chmod 0644 distrib/etc/*
	chmod 0755 distrib/lib/*
	chmod 0700 distrib/var/db
	chmod 0600 distrib/var/db/*
	chmod 0700 distrib/var/files
	chmod 0600 distrib/var/files/*
	chmod 0644 distrib/var/htdocs/groupware/css/*
	chmod 0644 distrib/var/htdocs/groupware/help/*
	chmod 0644 distrib/var/htdocs/groupware/images/*
	chmod 0755 distrib/var/htdocs/groupware/images/menu2
	chmod 0644 distrib/var/htdocs/groupware/images/menu2/*
	chmod 0644 distrib/var/htdocs/groupware/javascript/*
	chmod 0644 distrib/var/htdocs/groupware/sounds/*
	chmod 0700 distrib/var/log
	chmod 0600 distrib/var/log/*
	chmod 0700 distrib/var/mail
	chmod 0600 distrib/var/mail/*
	chmod 0700 distrib/var/tmp
	chmod 0600 distrib/var/tmp/*

	touch --date="$FILEDATE" *
	touch --date="$FILEDATE" distrib/*
	touch --date="$FILEDATE" distrib/bin/*
	touch --date="$FILEDATE" distrib/cgi-bin/*
	touch --date="$FILEDATE" distrib/etc/*
	touch --date="$FILEDATE" distrib/lib/*
	touch --date="$FILEDATE" distrib/var/files/*
	touch --date="$FILEDATE" distrib/var/htdocs/*
	touch --date="$FILEDATE" distrib/var/htdocs/groupware/*
	touch --date="$FILEDATE" distrib/var/htdocs/groupware/css/*
	touch --date="$FILEDATE" distrib/var/htdocs/groupware/help/*
	touch --date="$FILEDATE" distrib/var/htdocs/groupware/images/*
	touch --date="$FILEDATE" distrib/var/htdocs/groupware/images/menu2/*
	touch --date="$FILEDATE" distrib/var/htdocs/groupware/javascript/*
	touch --date="$FILEDATE" distrib/var/htdocs/groupware/sounds/*
	cp -a distrib ${OUTFILE}
	tar zcf ${OUTFILE}.tar.gz ${OUTFILE}
	rm -rf ${OUTFILE}
	touch --date="$FILEDATE" *
}

case "$1" in
'clean')
	build_clean
	;;
'pack')
	build_pack
	;;
*)
	echo "Usage: $0 {clean|pack}"
esac
exit 0
