@ECHO OFF
DELTREE /Y DISTRIB\BIN\*.*
DELTREE /Y DISTRIB\LIB\*.*
MKDIR obj
CD CONFIG
NMAKE -C -F CONFIG.MAK
CD ..\DBUTIL
NMAKE -C -F DBUTIL.MAK
CD ..\SERVER
NMAKE -C -F SERVER.MAK

CD ..\MODULES
CD MOD_ADMIN
NMAKE -C -F MOD_ADMIN.MAK
CD ..
CD MOD_BOOKMARKS
NMAKE -C -F MOD_BOOKMARKS.MAK
CD ..
CD MOD_CALENDAR
NMAKE -C -F MOD_CALENDAR.MAK
CD ..
CD MOD_CALLS
NMAKE -C -F MOD_CALLS.MAK
CD ..
CD MOD_CONTACTS
NMAKE -C -F MOD_CONTACTS.MAK
CD ..
CD MOD_FILES
NMAKE -C -F MOD_FILES.MAK
CD ..
CD MOD_FORUMS
NMAKE -C -F MOD_FORUMS.MAK
CD ..
CD MOD_MAIL
NMAKE -C -F MOD_MAIL.MAK
CD ..
CD MOD_MESSAGES
NMAKE -C -F MOD_MESSAGES.MAK
CD ..
CD MOD_NOTES
NMAKE -C -F MOD_NOTES.MAK
CD ..
CD MOD_ORDERS
NMAKE -C -F MOD_ORDERS.MAK
CD ..
CD MOD_PROFILE
NMAKE -C -F MOD_PROFILE.MAK
CD ..
CD MOD_SEARCHES
NMAKE -C -F MOD_SEARCHES.MAK
CD ..
CD MOD_TASKS
NMAKE -C -F MOD_TASKS.MAK
CD ..
CD ..

COPY OTHER\SQLITE.DLL DISTRIB\LIB
