@ECHO OFF
REM DELTREE /Y DISTRIB\BIN\*.*
REM DELTREE /Y DISTRIB\LIB\*.*
MKDIR obj
CD WIN32
CD CONFIG
NMAKE /C /S /F CONFIG.MAK
CD ..\GWMON
NMAKE /C /S /F GWMON.MAK
CD ..
CD ..\DBUTIL
NMAKE /C /S /F DBUTIL.MAK
CD ..\SERVER
NMAKE /C /S /F SERVER.MAK
CD ..\MODULES
CALL MAKE.BAT
CD ..
COPY CONTRIB\LIBSQLITE.DLL DISTRIB\LIB
