@ECHO OFF
DELTREE /Y DISTRIB\BIN\*.*
DELTREE /Y DISTRIB\LIB\*.*
MKDIR obj
CD CONFIG
NMAKE /C /S /F CONFIG.MAK
CD ..\DBUTIL
NMAKE /C /S /F DBUTIL.MAK
CD ..\SERVER
NMAKE /C /S /F SERVER.MAK
CD ..\MODULES
CALL MAKE.BAT
CD ..
COPY CONTRIB\LIBSQLITE.DLL DISTRIB\LIB
