#!/bin/sh
FILEDATE="`date +%Y-%m-%d` 01:03"
OUTFILE=nullgroupware-1.3.30-x86
if [ "`uname`" = "FreeBSD" ]; then
	OUTFILE=$OUTFILE-freebsd
elif [ "`uname`" = "OpenBSD" ]; then
	OUTFILE=$OUTFILE-openbsd
elif [ "`uname`" = "Linux" ]; then
	if [ "`uname -r | awk -F'.' '{ print $1"."$2 }'`" = "2.0" ]; then
		OUTFILE=$OUTFILE-oldlinux-libc5
	else
		OUTFILE=$OUTFILE-linux
	fi
else
	OUTFILE=$OUTFILE-unknown
fi

build_pack() {
	rm -rf ${OUTFILE}
	rm -rf ${OUTFILE}.tar.gz
	cd scripts;touch --date="$FILEDATE" `find *`;cd ..
	cd distrib;touch --date="$FILEDATE" `find *`;cd ..
	cp -pR distrib ${OUTFILE}
	tar zcf ${OUTFILE}.tar.gz ${OUTFILE}
	rm -rf ${OUTFILE}
	touch --date="$FILEDATE" ${OUTFILE}.tar.gz
	md5sum ${OUTFILE}.tar.gz > ${OUTFILE}.txt
	echo "" >> ${OUTFILE}.txt
	file distrib/bin/nullgw-server >> ${OUTFILE}.txt
	ldd distrib/bin/nullgw-server >> ${OUTFILE}.txt
}

build_slackpack() {
	rm -rf slackroot
	rm -rf ${OUTFILE}.tgz
	cd distrib;touch --date="$FILEDATE" `find -name "*"`;cd ..
	mkdir -p slackroot/usr/local
	mkdir -p slackroot/install
	cp -pR distrib slackroot/usr/local/nullgroupware
	cat << EOF > slackroot/install/doinst.sh
( cd /usr/local/nullgroupware/bin ; ./nullgw-confutil )
EOF
	cat << EOF > slackroot/install/slack-desc
# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|'
# on the right side marks the last column you can put a character in.  You must
# make exactly 11 lines for the formatting to be correct.  It's also
# customary to leave one space after the ':'.


|-----handy-ruler------------------------------------------------------|
nullgroupware: nullgroupware
nullgroupware:
nullgroupware: NullLogic Groupware Server
nullgroupware:
nullgroupware: This is the NullLogic Groupware Server Suite written and maintained
nullgroupware: by Dan Cahill.
nullgroupware:
nullgroupware:
nullgroupware:
nullgroupware:
nullgroupware:
EOF
	chmod 755 slackroot/install/doinst.sh
	chmod 644 slackroot/install/slack-desc
	cd slackroot
	tar zcf ../${OUTFILE}.tgz *
	cd ..
	rm -rf slackroot
	touch --date="$FILEDATE" ${OUTFILE}.tgz
	md5sum ${OUTFILE}.tar.gz > ${OUTFILE}.txt
	echo "" >> ${OUTFILE}.txt
	file distrib/bin/nullgw-server >> ${OUTFILE}.txt
	ldd distrib/bin/nullgw-server >> ${OUTFILE}.txt
}

case "$1" in
'pack')
	build_pack
	;;
'slackpack')
	build_slackpack
	;;
*)
	echo "Usage: $0 {pack|slackpack}"
esac
exit 0
