#include "../../include/nsp/nsp.h"
#include "../../include/nsp/nsplib.h"
#include "../libnsp/opcodes.h"

#include "../libnsp/block.c"
#include "../libnsp/compile.c"
#include "../libnsp/debug.c"
#include "../libnsp/exec.c"
#include "../libnsp/libc.c"
#include "../libnsp/libn.c"
#include "../libnsp/objects.c"
#include "../libnsp/opcodes.c"
#include "../libnsp/parser.c"
//#include "../hosts/lite/main.c"
