#!/bin/sh
VERSION="3.5.1"

do_configure() {
	if [ ! -r "sqlite-$VERSION.tar.gz" ]; then
		echo "sqlite source not found"
		exit 0
	fi
	if [ ! -r "sqlite-$VERSION/configure" ]; then
		tar zxf sqlite-$VERSION.tar.gz
	fi
	mkdir -p build
	cd build
	if [ ! -r "Makefile" ]; then
		../sqlite-$VERSION/configure --enable-shared --disable-static --disable-tcl
	fi
}
#exit 0
case "$1" in
'build')
	do_configure
	if [ "`uname`" != "Linux" ]; then
		gmake -s
	else
		make -s
	fi
	cd ..
	if [ -r "build/.libs/libsqlite3.so.0.8.6" ]; then
		strip build/.libs/libsqlite3.so.0.8.6
		cp -p build/.libs/libsqlite3.so.0.8.6 ../../lib/libsqlite3.so
	elif [ -r "build/.libs/libsqlite3.so.8.6" ]; then
		strip build/.libs/libsqlite3.so.8.6
		cp -p build/.libs/libsqlite3.so.8.6 ../../lib/libsqlite3.so
	elif [ -r "build/.libs/libsqlite3.so.8" ]; then
		strip build/.libs/libsqlite3.so.8
		cp -p build/.libs/libsqlite3.so.8 ../../lib/libsqlite3.so
	fi
	;;
'clean')
	rm -rf sqlite-$VERSION
	rm -rf build
	;;
'configure')
	do_configure
	;;
*)
	echo "Usage: $0 {build|clean|configure}"
esac
exit 0
