#!/bin/sh
BASENAME="sqlite-autoconf"
VERSION="3140200"

do_configure() {
	if [ ! -r "${BASENAME}-${VERSION}.tar.gz" ]; then
		echo "sqlite source not found"
		exit 0
	fi
	if [ ! -r "${BASENAME}-${VERSION}/configure" ]; then
		tar zxf ${BASENAME}-${VERSION}.tar.gz
	fi
	if [ ! -r "${BASENAME}-${VERSION}/Makefile" ]; then
		cd ${BASENAME}-${VERSION} && CFLAGS="-Os" ./configure && cd ..
	fi
}
#exit 0
case "$1" in
'build')
	do_configure
	if [ "`uname`" != "Linux" ]; then
		cd ${BASENAME}-${VERSION} && gmake -s && cd ..
	else
		cd ${BASENAME}-${VERSION} && make -s && cd ..
	fi
	if [ -r "${BASENAME}-${VERSION}/.libs/libsqlite3.so.0.8.6" ]; then
		strip ${BASENAME}-${VERSION}/.libs/libsqlite3.so.0.8.6
		cp -p ${BASENAME}-${VERSION}/.libs/libsqlite3.so.0.8.6 ../../lib/libsqlite3.so
	elif [ -r "${BASENAME}-${VERSION}/.libs/libsqlite3.so.8.6" ]; then
		strip ${BASENAME}-${VERSION}/.libs/libsqlite3.so.8.6
		cp -p ${BASENAME}-${VERSION}/.libs/libsqlite3.so.8.6 ../../lib/libsqlite3.so
	elif [ -r "${BASENAME}-${VERSION}/.libs/libsqlite3.so.8" ]; then
		strip ${BASENAME}-${VERSION}/.libs/libsqlite3.so.8
		cp -p ${BASENAME}-${VERSION}/.libs/libsqlite3.so.8 ../../lib/libsqlite3.so
	fi
	;;
'clean')
	rm -rf ${BASENAME}-${VERSION}
	;;
'configure')
	do_configure
	;;
*)
	echo "Usage: $0 {build|clean|configure}"
esac
exit 0
