Document: nullgroupware
Title: Debian nullgroupware Manual
Author: <insert document author here>
Abstract: This manual describes what nullgroupware is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nullgroupware/nullgroupware.sgml.gz

Format: postscript
Files: /usr/share/doc/nullgroupware/nullgroupware.ps.gz

Format: text
Files: /usr/share/doc/nullgroupware/nullgroupware.text.gz

Format: HTML
Index: /usr/share/doc/nullgroupware/html/index.html
Files: /usr/share/doc/nullgroupware/html/*.html

  
