#!/bin/sh

do_configure() {
	if [ ! -r "sqlite-3.0.8.tar.gz" ]; then
		echo "sqlite source not found"
		exit 0
	fi
	if [ ! -r "sqlite/configure" ]; then
		tar zxf sqlite-3.0.8.tar.gz
	fi
	mkdir -p build
	cd build
	if [ ! -r "Makefile" ]; then
		../sqlite/configure --disable-static
	fi
}

case "$1" in
'build')
	do_configure
	if [ "`uname`" != "Linux" ]; then
		gmake -s
	else
		make -s
	fi
	cd ..
	if [ -r "build/.libs/libsqlite3.so.0.8.6" ]; then
		strip build/.libs/libsqlite3.so.0.8.6
		cp -p build/.libs/libsqlite3.so.0.8.6 ../distrib/lib/libsqlite.so
	elif [ -r "build/.libs/libsqlite3.so.8.6" ]; then
		strip build/.libs/libsqlite3.so.8.6
		cp -p build/.libs/libsqlite3.so.8.6 ../distrib/lib/libsqlite.so
	elif [ -r "build/.libs/libsqlite3.so.8" ]; then
		strip build/.libs/libsqlite3.so.8
		cp -p build/.libs/libsqlite3.so.8 ../distrib/lib/libsqlite.so
	fi
	;;
'clean')
	rm -rf sqlite
	rm -rf build
	;;
'configure')
	do_configure
	;;
*)
	echo "Usage: $0 {build|clean|configure}"
esac
exit 0
