#!/bin/sh
HAVE_DIALOG="no"
LOGFILE="/tmp/nullgw_install-`date +%s`.log"
DESTDIR="/usr/local/nullgroupware"
TMP=/tmp

do_copying() {
	if [ "$HAVE_DIALOG" = "yes" ]; then
		echo "Copying files to $DESTDIR ... "	1>>$LOGFILE 2>>$LOGFILE
	fi
	mkdir -p $DEST_BIN			1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $DEST_ETC			1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $DEST_LIB			1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $DEST_VAR			1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $DEST_VAR/backup		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $DEST_VAR/cgi-bin		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $DEST_VAR/db			1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $DEST_VAR/domains		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $DEST_VAR/htdocs		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $DEST_VAR/log			1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $DEST_VAR/spool		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $DEST_VAR/tmp			1>>$LOGFILE 2>>$LOGFILE
	cp -pR bin/* $DEST_BIN			1>>$LOGFILE 2>>$LOGFILE
	cp -pR etc/* $DEST_ETC			1>>$LOGFILE 2>>$LOGFILE
	cp -pR lib/* $DEST_LIB			1>>$LOGFILE 2>>$LOGFILE
	cp -pR var/* $DEST_VAR			1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/db/groupware.db		1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/log/core-access.log	1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/log/core-error.log	1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/log/ghttpd-access.log	1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/log/ghttpd-error.log	1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/log/httpd-access.log	1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/log/httpd-error.log	1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/log/pop3d-access.log	1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/log/pop3d-error.log	1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/log/smtpd-access.log	1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/log/smtpd-error.log	1>>$LOGFILE 2>>$LOGFILE
	touch $DEST_VAR/log/sql-error.log	1>>$LOGFILE 2>>$LOGFILE
	chmod 0755 $DEST_BIN			1>>$LOGFILE 2>>$LOGFILE
	chmod 0770 $DEST_ETC			1>>$LOGFILE 2>>$LOGFILE
	chmod 0755 $DEST_LIB			1>>$LOGFILE 2>>$LOGFILE
	chmod 0770 $DEST_VAR			1>>$LOGFILE 2>>$LOGFILE
	if [ "$HAVE_DIALOG" = "yes" ]; then
		echo "done." 1>>$LOGFILE 2>>$LOGFILE
	fi
	sleep 1
}

setup_console() {
	clear 2>/dev/null
	echo "NullLogic Groupware Installation"
	echo "================================"
	echo -n "Install to what directory? [$DESTDIR]: "
	read TMP
	if [ ! -z $TMP ]; then
		DESTDIR=$TMP
	fi
	# Copy files to destination
	echo ""
	echo -n "Copying files to $DESTDIR ... "
	DEST_BIN="$DESTDIR/bin"
	DEST_ETC="$DESTDIR/etc"
	DEST_LIB="$DESTDIR/lib"
	DEST_VAR="$DESTDIR/var"
	do_copying
	cat $LOGFILE
	echo "done."
}

setup_dialog() {
	if [ "`whoami`" != "root" ]; then
		dialog --yesno "\nNullLogic Groupware should be installed by root.\n\nDo you want to continue with the installation?" 12 70
		FLAG=$?
		if [ ! $FLAG = 0 -a ! $FLAG = 1 ]; then
			exit 1
		fi
		if [ $FLAG = 0 ]; then # yes
			dialog --msgbox "\nYou've been warned." 12 70
		else
			clear 2>/dev/null
			exit
		fi
	fi
	while [ 0 ]; do
		dialog --inputbox "\nInstall to what directory?\n" 10 70 $DESTDIR 2> $TMP/gw_tmpout
		if [ $? = 1 -o $? = 255 ]; then
			rm -f $TMP/tempmsg $TMP/gw_tmpout
			exit
		fi
		DESTDIR="`cat $TMP/gw_tmpout`"
		rm -f $TMP/tempmsg $TMP/gw_tmpout
		if [ ! "$DESTDIR" = "" ]; then
			break;
		fi
	done
	dialog --infobox "\nCopying files to $DESTDIR ..." 5 50
	DEST_BIN="$DESTDIR/bin"
	DEST_ETC="$DESTDIR/etc"
	DEST_LIB="$DESTDIR/lib"
	DEST_VAR="$DESTDIR/var"
	do_copying
	clear 2>/dev/null
}

case "$1" in
debian)
	DESTDIR="../debian/nullgroupware"
	DEST_BIN="$DESTDIR/usr/bin"
	DEST_ETC="$DESTDIR/etc/nullgw"
	DEST_LIB="$DESTDIR/usr/lib/nullgw"
	DEST_VAR="$DESTDIR/var/nullgw"
	do_copying
	exit
	;;
upgrade)
	if [ -x /etc/init.d/nullgroupware ]; then
		/etc/init.d/nullgroupware stop
	fi
	;;
esac

rm -f $LOGFILE
touch $LOGFILE
if [ -x /bin/dialog ]; then
	HAVE_DIALOG="yes"
	dialog --textbox README 21 76
	setup_dialog
elif [ -x /usr/bin/dialog ]; then
	HAVE_DIALOG="yes"
	dialog --textbox README 21 76
	setup_dialog
else
	echo
	echo "Press enter to read the README file."
	read TMP
	less README
	setup_console
fi
rm -f $LOGFILE

case "$1" in
upgrade)
	cd $DESTDIR/bin ; ./nullgw-config upgrade
	if [ -x /etc/init.d/nullgroupware ]; then
		/etc/init.d/nullgroupware start
	fi
	;;
*)
	cd $DESTDIR/bin ; ./nullgw-config
	echo "To reconfigure the server, run 'cd $DESTDIR/bin;./nullgw-config'."
	echo
	echo "To start the server, run 'cd $DESTDIR/bin;./nullgw-init start'."
	echo
esac

exit
