#!/bin/sh
HAVE_CONFIG="no"
HAVE_DIALOG="no"
LOGFILE="/tmp/nullgw_install-`date +%s`.log"
DEFAULT_PATH="/usr/local/nullgroupware"
TMP=/tmp

SERVER_DIR_BASE="$DEFAULT_PATH"

do_copying() {
	if [ "$HAVE_DIALOG" = "yes" ]; then
		echo "Copying files to $SERVER_DIR_BASE ... "	1>>$LOGFILE 2>>$LOGFILE
	fi
	mkdir -p $SERVER_DIR_BASE/bin			1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $SERVER_DIR_BASE/etc			1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $SERVER_DIR_BASE/lib			1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $SERVER_DIR_BASE/var			1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $SERVER_DIR_BASE/var/backup		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $SERVER_DIR_BASE/var/cgi-bin		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $SERVER_DIR_BASE/var/db		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $SERVER_DIR_BASE/var/domains		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $SERVER_DIR_BASE/var/htdocs		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $SERVER_DIR_BASE/var/log		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $SERVER_DIR_BASE/var/spool		1>>$LOGFILE 2>>$LOGFILE
	mkdir -p $SERVER_DIR_BASE/var/tmp		1>>$LOGFILE 2>>$LOGFILE
	cp -pR bin/* $SERVER_DIR_BASE/bin		1>>$LOGFILE 2>>$LOGFILE
	cp -pR etc/* $SERVER_DIR_BASE/etc		1>>$LOGFILE 2>>$LOGFILE
	cp -pR lib/* $SERVER_DIR_BASE/lib		1>>$LOGFILE 2>>$LOGFILE
	cp -pR var/* $SERVER_DIR_BASE/var		1>>$LOGFILE 2>>$LOGFILE
	touch $SERVER_DIR_BASE/var/db/groupware.db	1>>$LOGFILE 2>>$LOGFILE
	touch $SERVER_DIR_BASE/var/log/core-access.log	1>>$LOGFILE 2>>$LOGFILE
	touch $SERVER_DIR_BASE/var/log/core-error.log	1>>$LOGFILE 2>>$LOGFILE
	touch $SERVER_DIR_BASE/var/log/httpd-access.log	1>>$LOGFILE 2>>$LOGFILE
	touch $SERVER_DIR_BASE/var/log/httpd-error.log	1>>$LOGFILE 2>>$LOGFILE
	touch $SERVER_DIR_BASE/var/log/pop3d-access.log	1>>$LOGFILE 2>>$LOGFILE
	touch $SERVER_DIR_BASE/var/log/pop3d-error.log	1>>$LOGFILE 2>>$LOGFILE
	touch $SERVER_DIR_BASE/var/log/smtpd-access.log	1>>$LOGFILE 2>>$LOGFILE
	touch $SERVER_DIR_BASE/var/log/smtpd-error.log	1>>$LOGFILE 2>>$LOGFILE
	touch $SERVER_DIR_BASE/var/log/sql-error.log	1>>$LOGFILE 2>>$LOGFILE
	chmod 0755 $SERVER_DIR_BASE/bin			1>>$LOGFILE 2>>$LOGFILE
	chmod 0755 $SERVER_DIR_BASE/bin/*		1>>$LOGFILE 2>>$LOGFILE
	chmod 0700 $SERVER_DIR_BASE/etc			1>>$LOGFILE 2>>$LOGFILE
	chmod 0755 $SERVER_DIR_BASE/lib			1>>$LOGFILE 2>>$LOGFILE
	chmod 0700 $SERVER_DIR_BASE/var			1>>$LOGFILE 2>>$LOGFILE
	if [ "$HAVE_DIALOG" = "yes" ]; then
		echo "done." 1>>$LOGFILE 2>>$LOGFILE
	fi
	sleep 1
}

setup_console() {
	clear 2>/dev/null
	echo "NullLogic Groupware Installation"
	echo "================================"
	echo -n "Install to what directory? [$SERVER_DIR_BASE]: "
	read TMP
	if [ ! -z $TMP ]; then
		SERVER_DIR_BASE=$TMP
	fi
	# Copy files to destination
	echo ""
	echo -n "Copying files to $SERVER_DIR_BASE ... "
	do_copying
	cat $LOGFILE
	echo "done."
}

setup_dialog() {
	if [ "`whoami`" != "root" ]; then
		dialog --yesno "\nNullLogic Groupware should be installed by root.\n\nDo you want to continue with the installation?" 12 70
		FLAG=$?
		if [ ! $FLAG = 0 -a ! $FLAG = 1 ]; then
			exit 1
		fi
		if [ $FLAG = 0 ]; then # yes
			dialog --msgbox "\nYou've been warned." 12 70
		else
			clear 2>/dev/null
			exit
		fi
	fi
	while [ 0 ]; do
		dialog --inputbox "\nInstall to what directory?\n" 10 70 $SERVER_DIR_BASE 2> $TMP/gw_tmpout
		if [ $? = 1 -o $? = 255 ]; then
			rm -f $TMP/tempmsg $TMP/gw_tmpout
			exit
		fi
		SERVER_DIR_BASE="`cat $TMP/gw_tmpout`"
		rm -f $TMP/tempmsg $TMP/gw_tmpout
		if [ ! "$SERVER_DIR_BASE" = "" ]; then
			break;
		fi
	done
	dialog --infobox "\nCopying files to $SERVER_DIR_BASE ..." 5 50
	do_copying
	clear 2>/dev/null
}

rm -f $LOGFILE
touch $LOGFILE
if [ -x /bin/dialog ]; then
	HAVE_DIALOG="yes"
	dialog --textbox README 21 76
	setup_dialog
elif [ -x /usr/bin/dialog ]; then
	HAVE_DIALOG="yes"
	dialog --textbox README 21 76
	setup_dialog
else
	echo
	echo "Press enter to read the README file."
	read TMP
	less README
	setup_console
fi
rm -f $LOGFILE

case "$1" in
upgrade)
	cd $SERVER_DIR_BASE/bin ; ./nullgw-config upgrade
	;;
*)
	cd $SERVER_DIR_BASE/bin ; ./nullgw-config
	echo "To reconfigure the server, run 'cd $SERVER_DIR_BASE/bin;./nullgw-config'."
	echo
	echo "To start the server, run 'cd $SERVER_DIR_BASE/bin;./rc.groupware start'."
	echo
esac

exit
