#!/bin/sh
RUN_AS_USER="groupware"
RUN_AS_GROUP="groupware"
INSTALL_PATH="/usr/local/groupware"
SERVER_LOGLEVEL="1"
SERVER_HOSTNAME="localhost"
SERVER_PORT="4110"
SQL_TYPE="SQLITE"
SQL_HOSTNAME="localhost"
SQL_DBNAME="groupware"
SQL_USERNAME="groupware"
SQL_PASSWORD="password"

clear 2>/dev/null
echo "NullLogic Groupware Configuration"
echo "================================="
# Get config information
echo -n "Install to what directory? [$INSTALL_PATH]: "
read TMP
if [ ! -z $TMP ]; then
	INSTALL_PATH=$TMP
fi
echo -n "Will you be using SQLITE, MYSQL or PGSQL [$SQL_TYPE]: "
read TMP
if [ ! -z $TMP ]; then
	SQL_TYPE=$TMP
fi
case "$SQL_TYPE" in
	MYSQL)
	SQL_PORT="3306"
	SQL_USERNAME="mysql"
	;;
	PGSQL)
	SQL_PORT="5432"
	SQL_USERNAME="postgres"
	;;
	SQLITE)
	SQL_PORT="0"
	SQL_USERNAME=""
	;;
	*)
	echo "Unknown SQL server type $SQL_TYPE. Exiting."
	exit
	;;
esac

case "$SQL_TYPE" in
	SQLITE)
	SQL_PORT="0"
	SQL_USERNAME=""
	SQL_HOSTNAME=""
	SQL_DBNAME=""
	SQL_USERNAME=""
	SQL_PASSWORD=""
	;;
	*)
	echo -n "What is the host name of the $SQL_TYPE server? [$SQL_HOSTNAME]: "
	read TMP
	if [ ! -z $TMP ]; then
		SQL_HOSTNAME=$TMP
	fi
	echo -n "What TCP/IP port is the $SQL_TYPE server listening on? [$SQL_PORT]: "
	read TMP
	if [ ! -z $TMP ]; then
		SQL_PORT=$TMP
	fi
	echo -n "What is the name of the database Null Groupware should use? [$SQL_DBNAME]: "
	read TMP
	if [ ! -z $TMP ]; then
		SQL_DBNAME=$TMP
	fi
	echo -n "What username should Null Groupware use to access the database? [$SQL_USERNAME]: "
	read TMP
	if [ ! -z $TMP ]; then
		SQL_USERNAME=$TMP
	fi
	echo -n "What is the password for the '$SQL_USERNAME' account? [$SQL_PASSWORD]: "
	read TMP
	if [ ! -z $TMP ]; then
		SQL_PASSWORD=$TMP
	fi
	;;
esac

# Copy files to destination
echo -n "Copy Null Groupware files to $INSTALL_PATH..."
mkdir -p $INSTALL_PATH/bin
mkdir -p $INSTALL_PATH/cgi-bin
mkdir -p $INSTALL_PATH/etc
mkdir -p $INSTALL_PATH/files
mkdir -p $INSTALL_PATH/htdocs
cp -a bin/* $INSTALL_PATH/bin
cp -a cgi-bin/* $INSTALL_PATH/cgi-bin
cp -a etc/* $INSTALL_PATH/etc
cp -a files/* $INSTALL_PATH/files
cp -a htdocs/* $INSTALL_PATH/htdocs
cp -a COPYRIGHT.txt $INSTALL_PATH
cp -a README.txt $INSTALL_PATH
touch $INSTALL_PATH/etc/access.log
touch $INSTALL_PATH/etc/error.log
touch $INSTALL_PATH/etc/groupware.db
chmod 0755 $INSTALL_PATH -R
chmod 0644 $INSTALL_PATH/COPYRIGHT.txt
chmod 0644 $INSTALL_PATH/README.txt
chmod 0755 $INSTALL_PATH/bin/*
chmod 0755 $INSTALL_PATH/cgi-bin/*
chmod 0600 $INSTALL_PATH/etc/*
chmod 0644 $INSTALL_PATH/files/*
chmod 0644 $INSTALL_PATH/htdocs/groupware/css/*
chmod 0644 $INSTALL_PATH/htdocs/groupware/help/*
chmod 0644 $INSTALL_PATH/htdocs/groupware/images/*
chmod 0755 $INSTALL_PATH/htdocs/groupware/images/menu2
chmod 0644 $INSTALL_PATH/htdocs/groupware/images/menu2/*
chmod 0644 $INSTALL_PATH/htdocs/groupware/javascript/*
chmod 0644 $INSTALL_PATH/htdocs/groupware/sounds/*

# Write groupware.cfg configuration file
echo -e "# This file contains settings for Null Groupware."	> $INSTALL_PATH/etc/groupware.cfg
echo -e ""							>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SERVER_BASE_DIR   = \"$INSTALL_PATH\""			>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SERVER_BIN_DIR    = \"$INSTALL_PATH/bin\""		>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SERVER_CGI_DIR    = \"$INSTALL_PATH/cgi-bin\""		>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SERVER_ETC_DIR    = \"$INSTALL_PATH/etc\""		>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SERVER_FILE_DIR   = \"$INSTALL_PATH/files\""		>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SERVER_HTDOCS_DIR = \"$INSTALL_PATH/htdocs\""		>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SERVER_LOGLEVEL   = \"1\""				>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SERVER_HOSTNAME   = \"$SERVER_HOSTNAME\""		>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SERVER_PORT       = \"4110\""				>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SERVER_MAX_CONN   = \"50\""				>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SERVER_MAX_IDLE   = \"300\""				>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SQL_TYPE          = \"$SQL_TYPE\""			>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SQL_HOSTNAME      = \"$SQL_HOSTNAME\""			>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SQL_PORT          = \"$SQL_PORT\""			>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SQL_DBNAME        = \"$SQL_DBNAME\""			>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SQL_USERNAME      = \"$SQL_USERNAME\""			>> $INSTALL_PATH/etc/groupware.cfg
echo -e "SQL_PASSWORD      = \"$SQL_PASSWORD\""			>> $INSTALL_PATH/etc/groupware.cfg
chmod 0600 $INSTALL_PATH/etc/groupware.cfg

useradd -c "Null Groupware" -d $INSTALL_PATH/bin $RUN_AS_USER 2>/dev/null
groupadd $RUN_AS_GROUP 2>/dev/null
chown $RUN_AS_USER.$RUN_AS_GROUP $INSTALL_PATH/etc -R
chown $RUN_AS_USER.$RUN_AS_GROUP $INSTALL_PATH/files -R

echo "done."
echo
echo "Press enter to read the README file."
read TMP
less README.txt
clear 2>/dev/null
echo "In order to complete the install, you will need to manually create the"
echo "SQL database $SQL_DBNAME as follows."
case "$SQL_TYPE" in
	MYSQL)
	echo "  mysqladmin create $SQL_DBNAME"
	;;
	PGSQL)
	echo "  createdb $SQL_DBNAME"
	;;
	*)
	echo
	;;
esac
echo "After creating the database, please run $INSTALL_PATH/bin/dbutil to"
echo "initialise the database."
echo
echo "To start the server, run '$INSTALL_PATH/bin/groupware'."
echo
cd ${INSTALL_PATH}/bin
