# Makefile for NullLogic Groupware mods

include ../../Rules.mak

all:
	@echo " mod_admin"      ; cd mod_admin      ; $(MAKE)
	@echo " mod_accounting" ; cd mod_accounting ; $(MAKE)
	@echo " mod_bookmarks"  ; cd mod_bookmarks  ; $(MAKE)
	@echo " mod_calendar"   ; cd mod_calendar   ; $(MAKE)
	@echo " mod_calls"      ; cd mod_calls      ; $(MAKE)
	@echo " mod_cgi"        ; cd mod_cgi        ; $(MAKE) 
	@echo " mod_contacts"   ; cd mod_contacts   ; $(MAKE)
	@echo " mod_files"      ; cd mod_files      ; $(MAKE)
	@echo " mod_forums"     ; cd mod_forums     ; $(MAKE)
	@echo " mod_html"       ; cd mod_html       ; $(MAKE)
	@echo " mod_mail"       ; cd mod_mail       ; $(MAKE)
	@echo " mod_messages"   ; cd mod_messages   ; $(MAKE)
	@echo " mod_notes"      ; cd mod_notes      ; $(MAKE)
	@echo " mod_orders"     ; cd mod_orders     ; $(MAKE)
#	@echo " mod_php"        ; cd mod_php        ; $(MAKE)
	@echo " mod_profile"    ; cd mod_profile    ; $(MAKE)
	@echo " mod_projects"   ; cd mod_projects   ; $(MAKE)
	@echo " mod_searches"   ; cd mod_searches   ; $(MAKE)
	@echo " mod_tasks"      ; cd mod_tasks      ; $(MAKE)
	@echo " mod_xmlrpc"     ; cd mod_xmlrpc     ; $(MAKE)

clean:
	@cd mod_admin      ; $(MAKE) clean
	@cd mod_accounting ; $(MAKE) clean
	@cd mod_bookmarks  ; $(MAKE) clean
	@cd mod_calendar   ; $(MAKE) clean
	@cd mod_calls      ; $(MAKE) clean
	@cd mod_cgi        ; $(MAKE) clean
	@cd mod_contacts   ; $(MAKE) clean
	@cd mod_files      ; $(MAKE) clean
	@cd mod_forums     ; $(MAKE) clean
	@cd mod_html       ; $(MAKE) clean
	@cd mod_mail       ; $(MAKE) clean
	@cd mod_messages   ; $(MAKE) clean
	@cd mod_notes      ; $(MAKE) clean
	@cd mod_orders     ; $(MAKE) clean
#	@cd mod_php        ; $(MAKE) clean
	@cd mod_profile    ; $(MAKE) clean
	@cd mod_projects   ; $(MAKE) clean
	@cd mod_searches   ; $(MAKE) clean
	@cd mod_tasks      ; $(MAKE) clean
	@cd mod_xmlrpc     ; $(MAKE) clean
	@rm -f *~
