# Makefile for NullLogic Groupware mods

include ../../Rules.mak

all:
	@echo " mod_cgi"        ; cd mod_cgi        ; $(MAKE) 
#	@echo " mod_php"        ; cd mod_php        ; $(MAKE)

clean:
	@cd mod_cgi        ; $(MAKE) clean
#	@cd mod_php        ; $(MAKE) clean
	@rm -f *~
